@host=localhost:4004
@id=35df4384-7edc-4a64-b386-bd6cfff5223a
@customerId=c1545fa7-0828-49c2-9e1b-1e81f579a4ff
@productId=e6ce7144-0a3d-469e-9c20-8449559939f0

GET http://{{host}}/odata/v4/main/SalesOrderHeaders?$filter=id eq {{id}}&$expand=items
Content-Type: application/json

###

POST http://{{host}}/odata/v4/main/SalesOrderHeaders
Content-Type: application/json

{
    "id": "{{id}}",
    "customer_id": "{{customerId}}",
    "totalAmount": 4.98,
    "items": [
        {
            "id": "c4bd582a-dfb3-4910-a1ea-c3c410602602",
            "header_id": "{{id}}",
            "product_id": "{{productId}}",
            "quantity": 10,
            "price": 2.99
        },
        {
            "id": "715e4dec-e829-4267-ae46-40857a629104",
            "header_id": "{{id}}",
            "product_id": "{{productId}}",
            "quantity": 5,
            "price": 1.99
        }
    ]
}

###

PUT http://{{host}}/odata/v4/main/SalesOrderHeaders({{id}})
Content-Type: application/json

{
    "modifiedBy": "Teste"
}

###

DELETE http://{{host}}/odata/v4/main/SalesOrderHeaders({{id}})
Content-Type: application/json