@host=localhost:4004
@id=35df4384-7edc-4a64-b386-bd6cfff5223a

GET http://{{host}}/odata/v4/main/SalesOrderHeaders
Content-Type: application/json

###

POST http://{{host}}/odata/v4/main/SalesOrderHeaders
Content-Type: application/json

{}

###

PUT http://{{host}}/odata/v4/main/SalesOrderHeaders({{id}})
Content-Type: application/json

{
    "modifiedBy": "Teste"
}

###

DELETE http://{{host}}/odata/v4/main/SalesOrderHeaders({{id}})
Content-Type: application/json